name = "Product Customizer"
client_id = "2a361ddbfb4088e709762a50906089bd"
application_url = "https://your-production-url.com"
embedded = true

[access_scopes]
scopes = "write_products,read_products,write_themes,read_themes,write_script_tags,read_script_tags"

[auth]
redirect_urls = [
  "https://your-production-url.com/auth/callback",
  "https://your-production-url.com/ExitIframe"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
dev_store_url = "your-store.myshopify.com"

[[extensions]]
type = "theme_app_extension"
name = "Product Customizer"
handle = "product-customizer"

[extensions.targeting]
target = "section"
module = "product-customizer"

[extensions.capabilities]
block_types = ["product"]
allow_same_page = true

[extensions.settings]
default_locale = "en"