# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Product Customizer"
client_id = "2a361ddbfb4088e709762a50906089bd"
application_url = "https://localhost:3000"
embedded = true

[access_scopes]
scopes = "write_products,read_products,write_themes,read_themes,write_script_tags,read_script_tags"

[auth]
redirect_urls = [
  "https://localhost:3000/auth/callback",
  "https://localhost:3000/ExitIframe"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
dev_store_url = "your-store.myshopify.com"
