type = "theme_app_extension"
name = "Product Customizer"

[[extensions]]
type = "theme_app_extension"
name = "Product Customizer"
handle = "product-customizer"

[extensions.targeting]
target = "section"
module = "product-customizer"

[extensions.capabilities]
block_types = ["product"]

[extensions.settings]
target = "product"