type = "theme_app_extension"
name = "Product Customizer"
handle = "product-customizer"
 
[[extensions]]
type = "theme_app_extension"
name = "Product Customizer Block"
handle = "product-customizer-block"
target = "products"
 
[extensions.capabilities]
block_types = ["product", "section"]
 
[extensions.settings]
type = "object"
fields = [
  { key = "template", type = "string", label = "Customization Template" }
]