type = "theme_app_extension"
name = "Product Customizer"

[[extensions]]
type = "theme_app_extension"
name = "Product Customizer"
handle = "product-customizer"

[extensions.settings]
target = "section"

[extensions.capabilities]
block_types = ["product"]
settings_schema = true

[[extensions.extension_points]]
target = "product"
module = "./blocks/app-block"